# Generated by Django 4.2.3 on 2023-08-09 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_ebooks__id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ebooks", old_name="username", new_name="title",
        ),
    ]
