# Generated by Django 4.2.3 on 2023-08-09 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_rename_username_ebooks_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="authors",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
