# Generated by Django 4.2.3 on 2023-08-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_authors_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={"abstract": False,},
        ),
    ]
