# Generated by Django 4.2.3 on 2023-08-09 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_test"),
    ]

    operations = [
        migrations.RemoveField(model_name="test", name="id",),
        migrations.AddField(
            model_name="test",
            name="_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
