# Generated by Django 4.2.3 on 2023-08-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_ebooks_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="ebooks", name="is_active",),
        migrations.AddField(
            model_name="authors",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
