# Generated by Django 4.2.3 on 2023-08-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_remove_ebooks_is_active_authors_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
