# Generated by Django 4.2.3 on 2023-08-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_test_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="picture",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
