# Generated by Django 4.2.3 on 2023-08-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_test_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebooks",
            name="cover",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
