# Generated by Django 4.2.3 on 2023-08-16 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_authors_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="test4",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("pictures", models.ImageField(upload_to="images/")),
                (
                    "img_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="store.test",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
